### ISSUE TITLE
Add an upload button to the interface

### ISSUE THREAD

**Issue by tngan** [swri-robotics/bag-database#50] opened 2016-09-29 09:50 UTC
Is it possible to make an upload button to the interface ? It would allow admin/users to upload the files instead of directly access the folder or using FTP. It would be good if you are welcome pull request.

**Comment by pjreed** [comment] 2016-09-30 14:07
This is a duplicate of #7.

I've had a couple of people request this so I'll make it higher-priority on my list of things to do.  If you'd like to do it, pull requests are welcome. :smile:

**Closed by pjreed** 2016-09-30 14:07 UTC
